---
title: "Urban Heated Island System - OneNYC 2050"
author: "Boxuan Zhao, Yinhao Zhan, Yujin Pan, Zhiwei Huang, Yuxi Zheng"
institute: "UCL,CASA"
Group Name: "UPNO.1"
date: "3/22/2023"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: "xaringan-themer.css"
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_light(
  base_color = "#23395b",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "400", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```
## Sensor summary

## first time by zhiwei cc

## second by zhiwei

### What is the Synthetic Aperture Radar (SAR)

---
page 11

# 2.4 Why the products are useful?

## Their usefulness


---
page 13

# 2.4 Why the products are useful?

## Their usefulness

- Helping the government better monitor urban heat island conditions.

- Provide timely warnings and take countermeasures to reduce the impact of hot weather.

- Reduce casualties and damage caused by hot weather.

- Support urban planning and management by providing information of urban heat islands.

- Help government decision-makers to formulate urban planning and management policies better.

## Innovations

- Display data and information on urban heat islands through visualisation.

- Instant communication.

- Make intelligent predictions and warnings through artificial intelligence technology.

- Extensibility of platform functionality.

---
page 14

# 3.1 Possible risks and strtegies

## Their usefulness

Helping the government better monitor urban heat island conditions.

## Innovations

Display data and information on urban heat islands through visualisation.

## Innovations

Display data and information on urban heat islands through visualisation.





